name: Update Test Results

on:
  workflow_dispatch

jobs:
  update-test-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: devopselvis/github-pages-demo-test-results
          token: ${{ secrets.PAT }} # You should set this secret in your repo settings

      
      - name: Update test results
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)
          DATE=$(date +%Y-%m-%d)
          mkdir -p $SHORT_SHA-$DATE/test-results/test-results-details
          echo "<ul>" > $SHORT_SHA-$DATE/test-results/test-results-summary.html
          for i in {1..3}; do
            echo "$i $(date)" > $SHORT_SHA-$DATE/test-results/test-results-details/$i.html
            echo "<li><a href=\"test-results-details/$i.html\">Test $i</a></li>" >> $SHORT_SHA-$DATE/test-results/test-results-summary.html
          done
          echo "</ul>" >> $SHORT_SHA-$DATE/test-results/test-results-summary.html
          echo "<a href=\"$SHORT_SHA-$DATE/test-results/test-results-summary.html\">Test Results Summary</a><br>" >> index.html

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update test results" -a
          git push